/**
 * Canonical secret-detection pattern catalog.
 * Used by both the server-side /api/scan-file route and (mirrored inline) FileUpload.js.
 *
 * Each entry:
 *   id          — stable machine key
 *   name        — human label shown in the UI
 *   severity    — 'CRITICAL' | 'HIGH' | 'MEDIUM'
 *   regex       — detection pattern (re-instantiated per scan to reset lastIndex)
 *   redaction   — placeholder text that replaces the match
 *   why         — one-sentence explanation shown in the pattern catalog GET response
 */
export const SECRET_PATTERNS = [
  {
    id:        'google_api_key',
    name:      'Google API Key',
    severity:  'CRITICAL',
    regex:     /AIza[0-9A-Za-z\-_]{10,}/g,
    redaction: '[GOOGLE_API_KEY_REDACTED]',
    why:       'Exposes Google Cloud services; can incur large billing charges.',
  },
  {
    id:        'openai_key',
    name:      'OpenAI API Key',
    severity:  'CRITICAL',
    regex:     /sk-[A-Za-z0-9]{20,}/g,
    redaction: '[OPENAI_KEY_REDACTED]',
    why:       'Grants full OpenAI API access including GPT-4 and fine-tuning.',
  },
  {
    id:        'aws_access_key',
    name:      'AWS Access Key ID',
    severity:  'CRITICAL',
    regex:     /AKIA[0-9A-Z]{16}/g,
    redaction: '[AWS_KEY_REDACTED]',
    why:       'AWS root-level key that can control any cloud resource in the account.',
  },
  {
    id:        'aws_secret_key',
    name:      'AWS Secret Access Key',
    severity:  'CRITICAL',
    regex:     /aws_secret_access_key\s*[:=]\s*['"]?[a-zA-Z0-9/+=]{40}['"]?/gi,
    redaction: '[AWS_SECRET_REDACTED]',
    why:       'AWS secret key corresponding to an access key.',
  },
  {
    id:        'stripe_secret_live',
    name:      'Stripe Live Secret Key',
    severity:  'CRITICAL',
    regex:     /sk_live_[a-zA-Z0-9]{8,}/g,
    redaction: '[STRIPE_LIVE_KEY_REDACTED]',
    why:       'Live Stripe key; exposes real payment processing and customer data.',
  },
  {
    id:        'stripe_secret_test',
    name:      'Stripe Test Secret Key',
    severity:  'HIGH',
    regex:     /sk_test_[a-zA-Z0-9]{8,}/g,
    redaction: '[STRIPE_TEST_KEY_REDACTED]',
    why:       'Test Stripe key; can still be used to probe API structure.',
  },
  {
    id:        'private_key',
    name:      'Private Key (PEM)',
    severity:  'CRITICAL',
    regex:     /-----BEGIN (RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY(?: BLOCK)?-----[\s\S]*?-----END (RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY(?: BLOCK)?-----/g,
    redaction: '[PRIVATE_KEY_REDACTED]',
    why:       'Cryptographic private key; enables impersonation and data decryption.',
  },
  {
    id:        'database_url',
    name:      'Database URL',
    severity:  'CRITICAL',
    regex:     /(mongodb(\+srv)?|postgresql|mysql):\/\/[^\s]+/gi,
    redaction: '[DB_URL_REDACTED]',
    why:       'Full DB connection string including credentials and host.',
  },
  {
    id:        'redis_url',
    name:      'Redis Connection String',
    severity:  'CRITICAL',
    regex:     /redis[s]?:\/\/[^\s]+/gi,
    redaction: '[REDIS_URL_REDACTED]',
    why:       'Redis connection string exposing caching layers and background queues.',
  },
  {
    id:        'amqp_url',
    name:      'AMQP / RabbitMQ URL',
    severity:  'CRITICAL',
    regex:     /amqp[s]?:\/\/[^\s]+/gi,
    redaction: '[AMQP_URL_REDACTED]',
    why:       'RabbitMQ/AMQP connection string exposing messaging infrastructure.',
  },
  {
    id:        'cloud_storage_url',
    name:      'Cloud Storage URL (S3/GCS)',
    severity:  'MEDIUM',
    regex:     /(s3|gs):\/\/[^\s]+/gi,
    redaction: '[CLOUD_STORAGE_REDACTED]',
    why:       'Cloud storage bucket URI which could expose sensitive stored data.',
  },
  {
    id:        'azure_storage_connection',
    name:      'Azure Storage Connection String',
    severity:  'CRITICAL',
    regex:     /DefaultEndpointsProtocol=(http|https);AccountName=.*;AccountKey=[a-zA-Z0-9+/=]+/gi,
    redaction: '[AZURE_STORAGE_REDACTED]',
    why:       'Azure Storage Account connection string with full access keys.',
  },
  {
    id:        'jwt_secret',
    name:      'JWT Secret',
    severity:  'HIGH',
    regex:     /jwt[_-]?secret[\s:=]+\S+/gi,
    redaction: '[JWT_SECRET_REDACTED]',
    why:       'Allows forging signed JWTs, bypassing authentication entirely.',
  },
  {
    id:        'bearer_token',
    name:      'Bearer Token',
    severity:  'HIGH',
    regex:     /Bearer [a-zA-Z0-9\-._~+/]+=*/g,
    redaction: '[AUTH_TOKEN_REDACTED]',
    why:       'Active auth token that can replay authenticated API requests.',
  },
  {
    id:        'password_literal',
    name:      'Password (literal)',
    severity:  'HIGH',
    regex:     /password[\s:=]+['"]?\S+['"]?/gi,
    redaction: '[PASSWORD_REDACTED]',
    why:       'Plain-text password assignment leaked in config or source code.',
  },
  {
    id:        'api_key_generic',
    name:      'Generic API Key',
    severity:  'MEDIUM',
    regex:     /(?:api[_-]?key|apikey)[\s:=]+['"]?\S+['"]?/gi,
    redaction: '[API_KEY_REDACTED]',
    why:       'Generic key assignment; actual risk depends on the target service.',
  },
  {
    id:        'internal_ip',
    name:      'Internal IP Address',
    severity:  'MEDIUM',
    regex:     /\b10\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+\b/g,
    redaction: '[INTERNAL_IP_REDACTED]',
    why:       'Exposes private network topology that aids lateral movement.',
  },
  {
    id:        'credit_card',
    name:      'Credit Card Number',
    severity:  'CRITICAL',
    regex:     /\b(?:4[0-9]{12}(?:[0-9]{3})?|(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\d{3})\d{11})\b/g,
    redaction: '[CARD_NUMBER_REDACTED]',
    why:       'PAN data; exposure violates PCI-DSS and risks financial fraud.',
  },
  {
    id:        'ssn',
    name:      'Social Security Number',
    severity:  'CRITICAL',
    regex:     /\b(?!000)(?!666)(?!9\d{2})\d{3}-(?!00)\d{2}-(?!0000)\d{4}\b/g,
    redaction: '[SSN_REDACTED]',
    why:       'US SSN; identity theft enabler and HIPAA/FERPA violation risk.',
  },
  {
    id:        'github_pat',
    name:      'GitHub Personal Access Token',
    severity:  'CRITICAL',
    regex:     /ghp_[a-zA-Z0-9]{36}/g,
    redaction: '[GITHUB_PAT_REDACTED]',
    why:       'GitHub access token granting full access to user repositories.',
  },
  {
    id:        'github_oauth',
    name:      'GitHub OAuth Access Token',
    severity:  'CRITICAL',
    regex:     /gho_[a-zA-Z0-9]{36}/g,
    redaction: '[GITHUB_OAUTH_REDACTED]',
    why:       'GitHub OAuth token for authenticated third-party app actions.',
  },
  {
    id:        'slack_token',
    name:      'Slack Token',
    severity:  'HIGH',
    regex:     /xox[baprs]-[0-9a-zA-Z]{10,48}/g,
    redaction: '[SLACK_TOKEN_REDACTED]',
    why:       'Slack token allowing messaging, reading, and team access.',
  },
  {
    id:        'slack_webhook',
    name:      'Slack Webhook',
    severity:  'HIGH',
    regex:     /https:\/\/hooks\.slack\.com\/services\/T[a-zA-Z0-9_]{8}\/B[a-zA-Z0-9_]{8}\/[a-zA-Z0-9_]{24}/g,
    redaction: '[SLACK_WEBHOOK_REDACTED]',
    why:       'Allows posting messages to Slack channels via incoming webhooks.',
  },
  {
    id:        'mailgun_api_key',
    name:      'Mailgun API Key',
    severity:  'HIGH',
    regex:     /key-[0-9a-zA-Z]{32}/g,
    redaction: '[MAILGUN_KEY_REDACTED]',
    why:       'Mailgun key allowing unauthorized sending/reading of emails.',
  },
  {
    id:        'twilio_api_key',
    name:      'Twilio API Key',
    severity:  'HIGH',
    regex:     /SK[0-9a-fA-F]{32}/g,
    redaction: '[TWILIO_KEY_REDACTED]',
    why:       'Twilio key allowing unauthorized SMS/voice communications.',
  },
  {
    id:        'square_access_token',
    name:      'Square Access Token',
    severity:  'CRITICAL',
    regex:     /sq0atp-[0-9A-Za-z\-_]{22}/g,
    redaction: '[SQUARE_TOKEN_REDACTED]',
    why:       'Square token exposing payment and business data.',
  },
  {
    id:        'square_oauth_secret',
    name:      'Square OAuth Secret',
    severity:  'CRITICAL',
    regex:     /sq0csp-[0-9A-Za-z\-_]{43}/g,
    redaction: '[SQUARE_SECRET_REDACTED]',
    why:       'Square OAuth secret for application authentication.',
  },
  {
    id:        'paypal_braintree_token',
    name:      'PayPal Braintree Access Token',
    severity:  'CRITICAL',
    regex:     /access_token\$production\$[0-9a-zA-Z]{16}\$[0-9a-fA-F]{32}/g,
    redaction: '[PAYPAL_TOKEN_REDACTED]',
    why:       'PayPal Braintree token exposing payment gateway access.',
  },
  {
    id:        'sendgrid_api_key',
    name:      'SendGrid API Key',
    severity:  'HIGH',
    regex:     /SG\.[0-9a-zA-Z\-_]{22}\.[0-9a-zA-Z\-_]{43}/g,
    redaction: '[SENDGRID_KEY_REDACTED]',
    why:       'SendGrid API key for email delivery platform.',
  },
  {
    id:        'discord_bot_token',
    name:      'Discord Bot Token',
    severity:  'HIGH',
    regex:     /[MN][a-zA-Z0-9_-]{23,28}\.[a-zA-Z0-9_-]{6}\.[a-zA-Z0-9_-]{27}/g,
    redaction: '[DISCORD_TOKEN_REDACTED]',
    why:       'Discord token allowing unauthorized bot impersonation and access.',
  },
  {
    id:        'discord_webhook',
    name:      'Discord Webhook',
    severity:  'HIGH',
    regex:     /https:\/\/discord\.com\/api\/webhooks\/[0-9]{17,19}\/[a-zA-Z0-9_-]+/g,
    redaction: '[DISCORD_WEBHOOK_REDACTED]',
    why:       'Discord webhook URL for sending automated messages.',
  },
  {
    id:        'shopify_access_token',
    name:      'Shopify Access Token',
    severity:  'CRITICAL',
    regex:     /shpat_[a-fA-F0-9]{32}/g,
    redaction: '[SHOPIFY_TOKEN_REDACTED]',
    why:       'Shopify access token to commerce platform APIs.',
  },
  {
    id:        'figma_pat',
    name:      'Figma Personal Access Token',
    severity:  'MEDIUM',
    regex:     /figd_[a-zA-Z0-9\-_]{43}/g,
    redaction: '[FIGMA_PAT_REDACTED]',
    why:       'Figma personal access token to design files.',
  },
  {
    id:        'gitlab_pat',
    name:      'GitLab Personal Access Token',
    severity:  'CRITICAL',
    regex:     /glpat-[0-9a-zA-Z\-_]{20}/g,
    redaction: '[GITLAB_PAT_REDACTED]',
    why:       'GitLab token granting access to repositories and pipelines.',
  },
  {
    id:        'npm_access_token',
    name:      'NPM Access Token',
    severity:  'CRITICAL',
    regex:     /npm_[a-zA-Z0-9]{36}/g,
    redaction: '[NPM_TOKEN_REDACTED]',
    why:       'NPM registry access token enabling package publishing.',
  },
  {
    id:        'telegram_bot_token',
    name:      'Telegram Bot API Token',
    severity:  'HIGH',
    regex:     /[0-9]{8,10}:[a-zA-Z0-9_-]{35}/g,
    redaction: '[TELEGRAM_TOKEN_REDACTED]',
    why:       'Telegram bot token for sending messages and reading updates.',
  },
  {
    id:        'asana_pat',
    name:      'Asana Personal Access Token',
    severity:  'MEDIUM',
    regex:     /1\/\d{16}\/[a-zA-Z0-9]{32}/g,
    redaction: '[ASANA_PAT_REDACTED]',
    why:       'Asana access token for project management APIs.',
  },
  {
    id:        'bitbucket_client_id',
    name:      'Bitbucket Client ID',
    severity:  'HIGH',
    regex:     /bitbucket[_-]?client[_-]?id[\s:=]+['"]?[A-Za-z0-9]{20,64}['"]?/gi,
    redaction: '[BITBUCKET_CLIENT_ID_REDACTED]',
    why:       'Bitbucket Client ID for OAuth.',
  },
  {
    id:        'datadog_access_token',
    name:      'Datadog Access Token',
    severity:  'HIGH',
    regex:     /(?:DD_API_KEY|DATADOG_API_KEY)[\s:=]+['"]?[a-fA-F0-9]{32}['"]?/gi,
    redaction: '[DATADOG_TOKEN_REDACTED]',
    why:       'Datadog API access token.',
  },
  {
    id:        'gcp_oauth',
    name:      'GCP OAuth 2.0 Client ID',
    severity:  'HIGH',
    regex:     /[0-9]+-[0-9a-zA-Z_]{32}\.apps\.googleusercontent\.com/g,
    redaction: '[GCP_OAUTH_REDACTED]',
    why:       'Google Cloud Platform OAuth Client ID.',
  },
  {
    id:        'google_service_account_key',
    name:      'Google Service Account Private Key',
    severity:  'CRITICAL',
    regex:     /"private_key"\s*:\s*"-----BEGIN PRIVATE KEY-----[\s\S]*?-----END PRIVATE KEY-----\\n"/g,
    redaction: '[GCP_SERVICE_ACCOUNT_KEY_REDACTED]',
    why:       'Service account JSON private key grants programmatic access to GCP resources.',
  },
  {
    id:        'gcp_api_key_literal',
    name:      'GCP API Key (literal assignment)',
    severity:  'HIGH',
    regex:     /(?:gcp|google)[_-]?api[_-]?key[\s:=]+['"]?AIza[0-9A-Za-z\-_]{10,}['"]?/gi,
    redaction: '[GCP_API_KEY_REDACTED]',
    why:       'Likely exposed Google API key in config variables.',
  },
  {
    id:        'azure_client_secret',
    name:      'Azure Client Secret',
    severity:  'CRITICAL',
    regex:     /azure[_-]?client[_-]?secret[\s:=]+['"]?[A-Za-z0-9~._-]{20,}['"]?/gi,
    redaction: '[AZURE_CLIENT_SECRET_REDACTED]',
    why:       'Azure AD client secret can be used to impersonate an application.',
  },
  {
    id:        'azure_tenant_id',
    name:      'Azure Tenant ID',
    severity:  'MEDIUM',
    regex:     /azure[_-]?tenant[_-]?id[\s:=]+['"]?[0-9a-fA-F-]{36}['"]?/gi,
    redaction: '[AZURE_TENANT_ID_REDACTED]',
    why:       'Azure tenant identifier can aid targeted attacks and recon.',
  },
  {
    id:        'firebase_server_key',
    name:      'Firebase Server Key',
    severity:  'CRITICAL',
    regex:     /AAAA[A-Za-z0-9_-]{7}:[A-Za-z0-9_-]{140}/g,
    redaction: '[FIREBASE_SERVER_KEY_REDACTED]',
    why:       'Firebase Cloud Messaging server key allows sending unauthorized notifications.',
  },
  {
    id:        'firebase_api_key',
    name:      'Firebase API Key',
    severity:  'HIGH',
    regex:     /firebase[_-]?api[_-]?key[\s:=]+['"]?AIza[0-9A-Za-z\-_]{10,}['"]?/gi,
    redaction: '[FIREBASE_API_KEY_REDACTED]',
    why:       'Firebase API key can expose backend project endpoints.',
  },
  {
    id:        'notion_internal_token',
    name:      'Notion Internal Integration Token',
    severity:  'HIGH',
    regex:     /secret_[A-Za-z0-9]{43}/g,
    redaction: '[NOTION_TOKEN_REDACTED]',
    why:       'Notion integration token can access pages and databases.',
  },
  {
    id:        'airtable_api_key',
    name:      'Airtable API Key',
    severity:  'HIGH',
    regex:     /(?:AIRTABLE_API_KEY|airtableApiKey)[\s:=]+['"]?key[A-Za-z0-9]{14}['"]?/g,
    redaction: '[AIRTABLE_KEY_REDACTED]',
    why:       'Airtable key can expose base records and metadata.',
  },
  {
    id:        'algolia_api_key',
    name:      'Algolia API Key',
    severity:  'HIGH',
    regex:     /algolia[_-]?api[_-]?key[\s:=]+['"]?[A-Za-z0-9]{20,}['"]?/gi,
    redaction: '[ALGOLIA_KEY_REDACTED]',
    why:       'Algolia key may allow query and indexing operations.',
  },
  {
    id:        'auth0_client_secret',
    name:      'Auth0 Client Secret',
    severity:  'CRITICAL',
    regex:     /auth0[_-]?client[_-]?secret[\s:=]+['"]?[A-Za-z0-9_-]{32,}['"]?/gi,
    redaction: '[AUTH0_CLIENT_SECRET_REDACTED]',
    why:       'Auth0 client secret can be abused to mint tokens.',
  },
  {
    id:        'okta_api_token',
    name:      'Okta API Token',
    severity:  'CRITICAL',
    regex:     /00[a-zA-Z0-9]{18,}\.[a-zA-Z0-9._-]{20,}/g,
    redaction: '[OKTA_TOKEN_REDACTED]',
    why:       'Okta token can manage identities and authentication policies.',
  },
  {
    id:        'jwt_literal',
    name:      'JWT Token Literal',
    severity:  'HIGH',
    regex:     /\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b/g,
    redaction: '[JWT_TOKEN_REDACTED]',
    why:       'Embedded JWTs can grant direct session or API access.',
  },
  {
    id:        'docker_registry_password',
    name:      'Docker Registry Password',
    severity:  'HIGH',
    regex:     /docker[_-]?password[\s:=]+['"]?\S+['"]?/gi,
    redaction: '[DOCKER_PASSWORD_REDACTED]',
    why:       'Docker registry credentials can allow malicious image pushes.',
  },
  {
    id:        'kubernetes_bearer_token',
    name:      'Kubernetes Bearer Token',
    severity:  'CRITICAL',
    regex:     /k8s[_-]?token[\s:=]+['"]?[A-Za-z0-9._-]{20,}['"]?/gi,
    redaction: '[K8S_TOKEN_REDACTED]',
    why:       'Kubernetes token may provide cluster control-plane access.',
  },
  {
    id:        'kubernetes_config_cert',
    name:      'Kubeconfig Client Certificate Data',
    severity:  'CRITICAL',
    regex:     /client-certificate-data:\s*[A-Za-z0-9+/=]{80,}/g,
    redaction: '[KUBECONFIG_CERT_REDACTED]',
    why:       'Embedded kubeconfig certificates can authenticate to clusters.',
  },
  {
    id:        'ssh_private_key_inline',
    name:      'OpenSSH Private Key',
    severity:  'CRITICAL',
    regex:     /-----BEGIN OPENSSH PRIVATE KEY-----[\s\S]*?-----END OPENSSH PRIVATE KEY-----/g,
    redaction: '[OPENSSH_PRIVATE_KEY_REDACTED]',
    why:       'SSH private keys enable direct host access and lateral movement.',
  },
  {
    id:        'rsa_private_key_inline',
    name:      'RSA Private Key',
    severity:  'CRITICAL',
    regex:     /-----BEGIN RSA PRIVATE KEY-----[\s\S]*?-----END RSA PRIVATE KEY-----/g,
    redaction: '[RSA_PRIVATE_KEY_REDACTED]',
    why:       'RSA private key exposure compromises encrypted communications.',
  },
  {
    id:        'pgp_private_key',
    name:      'PGP Private Key Block',
    severity:  'CRITICAL',
    regex:     /-----BEGIN PGP PRIVATE KEY BLOCK-----[\s\S]*?-----END PGP PRIVATE KEY BLOCK-----/g,
    redaction: '[PGP_PRIVATE_KEY_REDACTED]',
    why:       'PGP private key can decrypt protected messages and impersonate users.',
  },
  {
    id:        'openrouter_api_key',
    name:      'OpenRouter API Key',
    severity:  'CRITICAL',
    regex:     /(?:OPENROUTER_API_KEY|openrouterApiKey)[\s:=]+['"]?sk-or-v1-[A-Za-z0-9]{20,}['"]?/g,
    redaction: '[OPENROUTER_KEY_REDACTED]',
    why:       'OpenRouter key can run paid model requests and expose prompts.',
  },
  {
    id:        'anthropic_api_key',
    name:      'Anthropic API Key',
    severity:  'CRITICAL',
    regex:     /(?:ANTHROPIC_API_KEY|anthropicApiKey)[\s:=]+['"]?sk-ant-[A-Za-z0-9\-_]{20,}['"]?/g,
    redaction: '[ANTHROPIC_KEY_REDACTED]',
    why:       'Anthropic key provides model invocation and billing access.',
  },
  {
    id:        'huggingface_token',
    name:      'Hugging Face Access Token',
    severity:  'HIGH',
    regex:     /hf_[A-Za-z0-9]{30,}/g,
    redaction: '[HUGGINGFACE_TOKEN_REDACTED]',
    why:       'Hugging Face token can access private models and datasets.',
  },
  {
    id:        'pypi_api_token',
    name:      'PyPI API Token',
    severity:  'CRITICAL',
    regex:     /pypi-[A-Za-z0-9_-]{60,}/g,
    redaction: '[PYPI_TOKEN_REDACTED]',
    why:       'PyPI token can publish malicious package versions.',
  },
  {
    id:        'npm_auth_token_literal',
    name:      'NPM Auth Token (config literal)',
    severity:  'CRITICAL',
    regex:     /\/\/registry\.npmjs\.org\/:_authToken=\S+/g,
    redaction: '[NPM_AUTH_TOKEN_REDACTED]',
    why:       'NPM auth token in config enables unauthorized package publishing.',
  },
  {
    id:        'gitlab_runner_token',
    name:      'GitLab Runner Registration Token',
    severity:  'HIGH',
    regex:     /glrt-[A-Za-z0-9_-]{20,}/g,
    redaction: '[GITLAB_RUNNER_TOKEN_REDACTED]',
    why:       'Runner token can register rogue CI runners.',
  },
  {
    id:        'sonarqube_token',
    name:      'SonarQube Token',
    severity:  'MEDIUM',
    regex:     /sonar[_-]?token[\s:=]+['"]?[A-Za-z0-9]{24,}['"]?/gi,
    redaction: '[SONAR_TOKEN_REDACTED]',
    why:       'Sonar token can expose code-analysis results and project metadata.',
  },
  {
    id:        'sentry_dsn',
    name:      'Sentry DSN',
    severity:  'MEDIUM',
    regex:     /https:\/\/[a-f0-9]{32}@[a-zA-Z0-9.-]+\.ingest\.sentry\.io\/\d+/g,
    redaction: '[SENTRY_DSN_REDACTED]',
    why:       'Sentry DSN can be abused to flood error telemetry.',
  },
  {
    id:        'new_relic_license_key',
    name:      'New Relic License Key',
    severity:  'HIGH',
    regex:     /newrelic[_-]?license[_-]?key[\s:=]+['"]?[A-Za-z0-9]{40}['"]?/gi,
    redaction: '[NEW_RELIC_LICENSE_REDACTED]',
    why:       'New Relic license key can submit spoofed telemetry data.',
  },
  {
    id:        'cloudflare_api_token',
    name:      'Cloudflare API Token',
    severity:  'CRITICAL',
    regex:     /(?:CLOUDFLARE_API_TOKEN|cloudflareApiToken)[\s:=]+['"]?[A-Za-z0-9_-]{35,50}['"]?/g,
    redaction: '[CLOUDFLARE_TOKEN_REDACTED]',
    why:       'Cloudflare token can modify DNS, WAF, and edge settings.',
  },
  {
    id:        'digitalocean_pat',
    name:      'DigitalOcean Personal Access Token',
    severity:  'CRITICAL',
    regex:     /dop_v1_[A-Za-z0-9]{64}/g,
    redaction: '[DIGITALOCEAN_PAT_REDACTED]',
    why:       'DigitalOcean token can create and delete infrastructure resources.',
  },
  {
    id:        'linode_pat',
    name:      'Linode Personal Access Token',
    severity:  'HIGH',
    regex:     /linode[_-]?token[\s:=]+['"]?[A-Za-z0-9]{40,}['"]?/gi,
    redaction: '[LINODE_TOKEN_REDACTED]',
    why:       'Linode API token can control compute and networking resources.',
  },
  {
    id:        'planet_scale_password',
    name:      'PlanetScale Password',
    severity:  'CRITICAL',
    regex:     /(?:PLANETSCALE_PASSWORD|planetscalePassword)[\s:=]+['"]?[A-Za-z0-9._-]{20,}['"]?/g,
    redaction: '[PLANETSCALE_PASSWORD_REDACTED]',
    why:       'PlanetScale DB password can expose production data.',
  },
  {
    id:        'supabase_service_role',
    name:      'Supabase Service Role Key',
    severity:  'CRITICAL',
    regex:     /(?:SUPABASE_SERVICE_ROLE_KEY|supabaseServiceRoleKey)[\s:=]+['"]?eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+['"]?/g,
    redaction: '[SUPABASE_SERVICE_ROLE_REDACTED]',
    why:       'Supabase service role keys bypass row-level security restrictions.',
  }
];

/** Severity levels ranked lowest → highest for comparison. */
export const SEVERITY_RANK = { MEDIUM: 1, HIGH: 2, CRITICAL: 3 };

/** IDs considered "critical" for criticalCount tallying. */
export const CRITICAL_IDS = new Set(
  SECRET_PATTERNS.filter((p) => p.severity === 'CRITICAL').map((p) => p.id)
);
